apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd

spec:
  project: default

  sources:

  # Helm chart source
  - repoURL: https://github.com/boingloings33/nginx-service.git
    targetRevision: HEAD
    path: helm

    helm:
      valueFiles:
        - $values/environments/dev/nginx-values.yaml

  # Values repo
  - repoURL: https://github.com/boingloings33/platform-gitops.git
    targetRevision: HEAD
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true